name: Self Test

on:
  push:

jobs:
  self_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./
        with:
          base: '/test'
